// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBCcsx7lHQr8egkcyFjBEdXa-aD1HF_CvU',
    appId: '1:830894456248:web:bf69bb16b5d9d0fd95e34d',
    messagingSenderId: '830894456248',
    projectId: 'lapork',
    authDomain: 'lapork.firebaseapp.com',
    storageBucket: 'lapork.firebasestorage.app',
    measurementId: 'G-9QS0GVRM65',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbiK7MsdOUqg9TxpPwG6ZgIrmhh8f7T0o',
    appId: '1:830894456248:android:0d45309bb0f4cbc595e34d',
    messagingSenderId: '830894456248',
    projectId: 'lapork',
    storageBucket: 'lapork.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBCcsx7lHQr8egkcyFjBEdXa-aD1HF_CvU',
    appId: '1:830894456248:web:0022776512f0e72a95e34d',
    messagingSenderId: '830894456248',
    projectId: 'lapork',
    authDomain: 'lapork.firebaseapp.com',
    storageBucket: 'lapork.firebasestorage.app',
    measurementId: 'G-C80RQ99YN7',
  );
}
